@baseURL = http://localhost:8080

# @name createProduct
POST {{baseURL}}/products
Content-Type: application/json

{
  "name": "Product 3",
  "price": 300
}

###

# @name getProduct
GET {{baseURL}}/products/fa9b6da0-be21-4b7e-9de8-461163004598
Content-Type: application/json